apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.master.servicename" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
  {{- with .Values.master.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.master.service.type }}
  ports:
    - name: tcp-valkey
      port: {{ .Values.master.service.port }}
      targetPort: valkey
      protocol: TCP
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: master
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.replica.servicename" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: replica
  {{- with .Values.replica.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.replica.service.type }}
  ports:
    - name: tcp-valkey
      port: {{ .Values.replica.service.port }}
      targetPort: valkey
      protocol: TCP
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: replica
---
{{- if .Values.sentinel.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.sentinel.servicename" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: sentinel
spec:
  type: {{ .Values.sentinel.service.type }}
  ports:
    - name: tcp-sentinel
      port: {{ .Values.sentinel.service.port }}
      targetPort: sentinel
      protocol: TCP
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sentinel
{{- end }}
