apiVersion: v1
kind: Secret
metadata:
  name: {{ include "queue.fullname" . }}-secret
  labels:
    {{- include "queue.labels" . | nindent 4 }}
type: Opaque
data:
  KAFKA_USERNAME: {{ .Values.auth.username | b64enc | quote }}
  KAFKA_PASSWORD: {{ .Values.auth.password | b64enc | quote }}
  KAFKA_CLUSTER_ID: {{ .Values.auth.clusterId | b64enc | quote }}
