apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-secret
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.secrets.kafkaBootstrapServers | b64enc | quote }}
  KAFKA_USERNAME: {{ .Values.secrets.kafkaUsername | b64enc | quote }}
  KAFKA_PASSWORD: {{ .Values.secrets.kafkaPassword | b64enc | quote }}
  VALKEY_PASSWORD: {{ .Values.secrets.valkeyPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
